"""Streamlit Institutional Analytics presentation page."""

from collections.abc import Mapping
from typing import Any

import pandas as pd
import plotly.express as px
import streamlit as st

from application.controller import ANALYTICS_RESULT_SESSION_KEY, AnalyticsRunResult
from components.footer import render_footer
from config.schema import OVERALL_SCORE_COLUMN, RPI_COLUMN
from ui.theme import PRIMARY_TURQUOISE, apply_theme, render_brand_header, render_section_header


def render_institutional_analytics() -> None:
    """Render cached institutional statistics and completed analytics outputs."""
    apply_theme()
    render_brand_header("Institutional Analytics")
    result = st.session_state.get(ANALYTICS_RESULT_SESSION_KEY)
    if not isinstance(result, AnalyticsRunResult):
        st.info("Upload a valid synthetic EDOM CSV on the Dashboard Overview page first.")
        render_footer()
        return

    _render_summary_information(result)
    _render_descriptive_statistics(result.statistics)
    _render_rpi_distribution(result.analytics_data)
    _render_quartile_distribution(result.kpis["quartile_distribution"])
    _render_methodology()
    render_footer()


def _render_summary_information(result: AnalyticsRunResult) -> None:
    """Display the requested institutional summary values without recalculation."""
    render_section_header("Summary Information")
    kpis = result.kpis
    cards = st.columns(3)
    cards[0].metric("Total Lecturers", int(kpis["lecturer_count"]))
    cards[1].metric("Total Study Programs", int(kpis["study_program_count"]))
    cards[2].metric("Mean RPI", f"{float(kpis['average_rpi']):.2f}")
    cards = st.columns(3)
    cards[0].metric(
        "Standard Deviation",
        f"{result.statistics.standard_deviation[OVERALL_SCORE_COLUMN]:.2f}",
    )
    cards[1].metric("Highest RPI", f"{float(kpis['highest_rpi']):.2f}")
    cards[2].metric("Lowest RPI", f"{float(kpis['lowest_rpi']):.2f}")


def _render_descriptive_statistics(statistics: Any) -> None:
    """Display descriptive metrics generated by the Application Layer."""
    render_section_header("Descriptive Statistics")
    st.dataframe(_prepare_statistics_table(statistics), hide_index=True)


def _prepare_statistics_table(statistics: Any) -> pd.DataFrame:
    """Build a presentation table from the precomputed statistics result."""
    table = pd.DataFrame(
        {
            "Mean": statistics.mean,
            "Median": statistics.median,
            "Standard Deviation": statistics.standard_deviation,
            "Variance": statistics.variance,
            "Minimum": statistics.minimum,
            "Maximum": statistics.maximum,
        }
    )
    return table.rename_axis("Score").reset_index()


def _render_rpi_distribution(analytics_data: pd.DataFrame) -> None:
    """Display the completed analytics RPI values as a Plotly histogram."""
    render_section_header("RPI Distribution")
    figure = px.histogram(
        analytics_data,
        x=RPI_COLUMN,
        color_discrete_sequence=[PRIMARY_TURQUOISE],
    )
    st.plotly_chart(figure, use_container_width=True)


def _render_quartile_distribution(distribution: Mapping[str, int]) -> None:
    """Display precomputed quartile counts without reclassification."""
    render_section_header("Quartile Distribution")
    chart_data = pd.DataFrame(
        {"Quartile": list(distribution), "Lecturers": list(distribution.values())}
    )
    figure = px.bar(
        chart_data,
        x="Quartile",
        y="Lecturers",
        color_discrete_sequence=[PRIMARY_TURQUOISE],
    )
    st.plotly_chart(figure, use_container_width=True)


def _render_methodology() -> None:
    """Display a concise static description of the approved RPI method."""
    with st.expander("Methodology"):
        st.write(
            "Relative Performance Index (RPI) compares lecturer competency "
            "profiles within the institution."
        )
        st.write(
            "Rankit transformation converts dimension ranks into inverse-normal "
            "scores while preserving relative performance."
        )
        st.write(
            "T-score scaling expresses the combined index on a scale centred at "
            "50 with a standard deviation of 10."
        )


if __name__ == "__main__":
    render_institutional_analytics()
